### ISSUE TITLE
Bug fix for double chests

### ISSUE THREAD

**Issue by SoulLength** [Snakkos/CTransporter#1]
https://github.com/Snakkos/CTransporter/blob/80f7506a6169d857a99efbab5af38231818911e1/src/main/java/snakkos/github/io/ctransporter/PluginEvents.java#L57

Should be chest.get**Block**Inventory() to fix the double chest issue.

https://github.com/Snakkos/CTransporter/blob/80f7506a6169d857a99efbab5af38231818911e1/src/main/java/snakkos/github/io/ctransporter/PluginEvents.java#L74

Here as well.

**Comment by Snakkos** [comment]
I know you can't move double chests, but i prefer to leave it this way. It give the player the possibility to move only one part of the chest in case he don't want to move both. Anyway i noticed that when you place a chest near another one, they don't merge, so i'm working on a fix for this problem.

**Comment by SoulLength** [comment]
If you have a doublechest on the ground and you take the left chest with the tool you are clearing the whole doublechest inventory with getInventory().clear(), so the right chest (still on the ground) is being cleared as well. 
You should use getBlockInventory() since you can't take the whole doublechest. You will be able to take one half of the chest inventory that way (the one you are actually picking) and you will also leave the other chest intact (since you are calling clear() only on the half inventory you actually picked with the tool).
https://papermc.io/javadocs/paper/1.16/org/bukkit/block/Chest.html#getBlockInventory--

**Comment by Snakkos** [comment]
Thank you for your suggestion, i'll replace getInventory() with getBlockInventory() in the newer versions.
